# Generated by Django 2.2.5 on 2019-12-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='city_name',
        ),
    ]
